apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bench
  labels:
    app: k8s-bench
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-bench
  template:
    metadata:
      labels:
        app: k8s-bench
    spec:
      containers:
      - name: k8s-bench
        image: mansoor1/golang-bench:0.2
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "1"