apiVersion: v1
kind: Service
metadata:
  name: good-svc
  labels:
    app: good-svc
spec:
  selector:
    app: good-deploy
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: LoadBalancer